###################################################################
# JDevs                     v1.3.2                      Christmas #
# Christmas                                                 JDevs #
###################################################################

# При обновлении плагина, данная настройка может помочь обновить конфигурацию за вас. (Не удалять)
version: 1.1.0

# Значения:
# true - Включить
# false - Выключить
# null - Поставьте это, когда вам не нужно данное сообщение в чате

# Получить информацию о командах:
# /gifts

settings:
  # Настройки подарка
  gift:
    # Текстура головы base64 для подарка
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNlZjlhYTE0ZTg4NDc3M2VhYzEzNGE0ZWU4OTcyMDYzZjQ2NmRlNjc4MzYzY2Y3YjFhMjFhODViNyJ9fX0="
    # Лимит на подарки
    limit: true
    # Максимальное количество подарков с лимитом
    max: 5
    # В секундах. Через сколько удаляется подарок, если он не был использован.
    remove: 30
    # // Установите null, чтобы плагин заменил данные настройки на свои
    spawn:
      # Для версий 1.13+ (Настройка FallBlock по имени материала) Пример: "BARREL"
      type: "null"
      # Для версий ...-1.12.2 (Настройка FallBlock по id материала) Пример: "5"
      id: "null"
      # Использовать фейерверки?
      firework: true
      # В секундах. Сколько будет длиться жизнь FallBlock, если он не будет задействован?
      timeLived: 10
  # Настройки гринча
  grinch:
    # Включить?
    enabled: true
    # Шанс на подарок от гринча
    chance: 20
  # Настройки ресурсов
  loot:
    # Включить?
    enabled: true
    # Если подарок не был получен, то лут автоматически выпадает из него (Также при выключении)
    taked: false
  # Настройки голограммы
  holograms:
    # // Включение и выключение находится в launch.yml
    # Высота для голограммы
    height: 1.2
    # Строки голограммы
    # Форма плейсхолдеров для HolographicDisplays: {papi:%placeholder%}
    # Форма плейсхолдеров для DecentHolograms: %placeholder%
    # Заполнители:
    # %player% - Имя игрока.
    # %time% - Время до которого можно забрать подарок.
    lines:
      - "&cПодарок"
      - "&fНажми ПКМ, чтобы открыть!"
actions:
  # Действия:
  # [message] сообщение - Отправить сообщение игроку.
  # [broadcast] сообщение - Отправить сообщение всему серверу.
  # [player] команда - Выполнить команду от имени игрока.
  # [console] команда - Выполнить команду от имени консоли.
  # [sound] sound;volume;pitch - Выполнить звук для игрока
  # Звуки искать тут: https://helpch.at/docs/версия/org/bukkit/Sound.html
  # // Замените "версия" на версию вашего сервера, к примеру: https://helpch.at/docs/1.8/org/bukkit/Sound.html
  # [particle] type;amount;r.g.b;radius - Создайте частицы возле подарка
  # type:
  #   one - Частица, которая появляется в середине подарка.
  #   circle - Частицы, которые появляются вокруг подарка.
  # r.g.b (Подставьте значения RGB не убирая точки)
  # amount - Количество частиц в одной частице
  # radius - Поставьте радиус круга circle (0.1...)
  #
  # Встроенные функции:
  # %player% - Получить имя игрока
  # %rnd_player% - Получить имя случайного игрока
  gift:
    # При появлении подарка
    spawn:
      - "[message] &f"
      - "[message] &f&l✽ &aОт &aСанты Клауса&f пришел вам &cподарок &f— &cС новым годом! &f&l✽"
      - "[message] &f"
    # При потере подарка
    loss:
      - "[message] &f"
      - "[message] &f&l✽ &aСанта Клаус&f забрал &cподарок &f— &cТы забыл его забрать! &f&l✽"
      - "[message] &f"
    # Игрок успешно забрал подарок
    success:
      - "[message] &f&l✽ &r&fВы успешно забрали подарок"
    # Игрок достиг лимита подарков
    limit:
      - "[message] &f&l✽ &cВы уже забрали определённое кол-во подарков! :("
  # У игрока нет прав
  no_perm:
    - "[message] &f&l✽ &cУ вас недостаточно прав"

###############################################################
# JDevs                                             Christmas #
###############################################################