name: ChristmasGifts
version: '1.3.0'
main: dev.jdevs.JGifts.Christmas
authors: [ JDevs, Mitriyf ]
api-version: 1.13
softdepend: [DecentHolograms, HolographicDisplays, PlaceholderAPI, WorldGuard, WorldEdit]
commands:
  christmas:
    aliases: [ gifts ]