###################################################################
# JDevs                     v1.3.1                      Christmas #
# Christmas                                                 JDevs #
###################################################################

# When updating the plugin, this setting can help to update the configuration for you. (Do not delete)
version: 1.1.0

# Values:
# true - Enable
# false - Disable
# null - Set this when you don't need this message in the chat

# Get information about the teams:
# /gifts

settings:
  # Gift Settings
  gift:
    # Base64 head texture for gift
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNlZjlhYTE0ZTg4NDc3M2VhYzEzNGE0ZWU4OTcyMDYzZjQ2NmRlNjc4MzYzY2Y3YjFhMjFhODViNyJ9fX0="
    # Restriction on gifts
    limit: true
    # Maximum number of gifts
    max: 5
    # In seconds. After how long the gift is deleted if it has not been used.
    remove: 30
    spawn:
      # // Set null so that the plugin replaces these settings with its own
      # For 1.13+ (Setting the FallBlock view for the material) Example: "BARREL"
      type: "null"
      # For ...-1.12.2 (Setting up FallBlock material by id) Example: "5"
      id: "null"
      # Use of fireworks
      firework: true
      # In seconds. How long will FallBlock's life last if it is not activated?
      timeLived: 10
  # Grinch Settings
  grinch:
    # Enable?
    enabled: true
    # A chance for a gift from the grinch
    chance: 20
  # Resource Settings
  loot:
    # Enable?
    enabled: true
    # If the gift was not received, the loot automatically drops out of it (When turned off too)
    taked: false
  # Hologram Settings
  holograms:
    # // Enabling and disabling is in launch.yml
    # Height for a hologram
    height: 1.2
    # Hologram Lines
    lines:
      - "&cGift"
      - "&fPress the RMB to open it!"
actions:
  # Actions:
  # [message] message - Send a message to the player.
  # [broadcast] message - Send a message to all players
  # [player] command - Run the command on behalf of the player.
  # [console] command - Run the command on behalf of the console.
  # [sound] sound;volume;pitch - Perform a sound for the player
  # Search for sounds here: https://helpch.at/docs/$version$/org/bukkit/Sound.html
  # // Replace $version$ with the version of your server, for example: https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
  # [particle] type;amount;r.g.b;radius - Summon a particle near the gift
  # type:
  #   one - One particle will appear in place of the gift.
  #   circle - Particles will appear around the gift.
  # r.g.b (Substitute the RGB color without removing the dots)
  # amount - number
  # radius - You can set a decimal number (0.1...)
  #
  # Built-in functions:
  # %player% - Get the player's name
  # %rnd_player% - Get the name of a random player
  gift:
    # When a gift appears
    spawn:
      - "[message] &f"
      - "[message] &f&l✽ &aSanta Claus&f has sent you &ca gift &f— &cHappy New year! &f&l✽"
      - "[message] &f"
    # If you lose a gift
    loss:
      - "[message] &f"
      - "[message] &f&l✽ &aSanta Claus&f took &cthe gift &f— &cYou forgot to pick it up! &f&l✽"
      - "[message] &f"
    # The player has successfully collected the gift
    success:
      - "[message] &f&l✽ &r&fYou have successfully collected the gift"
    # The player has reached the gift limit
    limit:
      - "[message] &f&l✽ &cYou have already collected a certain number of gifts! :("
  # The player has no permission
  no_perm:
    - "[message] &f&l✽ &cYou don't have permission"

###############################################################
# JDevs                                             Christmas #
###############################################################